#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 29 14:06:54 2019

@author: rajdua
"""


import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix

train = pd.read_csv('train.csv')

kappas  = np.zeros(100)

for i in range(0,100):

    train['pred_response'] = np.random.randint(1, 9, train.shape[0])
    
    actual = train['Response']
    
    preds = train['pred_response']
    
    O = confusion_matrix(actual, preds)
    
    W = np.array([[0,1,2,3,4,5,6,7], [1,0,1,2,3,4,5,6], [2,1,0,1,2,3,4,5], [3,2,1,0,1,2,3,4],
                [4,3,2,1,0,1,2,3], [5,4,3,2,1,0,1,2], [6,5,4,3,2,1,0,1], [7,6,5,4,3,2,1,0]])
    
    act_hist = np.histogram(actual, bins = [1,2,3,4,5,6,7,8,9])[0]
 
    pred_hist = np.histogram(actual, bins = [1,2,3,4,5,6,7,8,9])[0]
         
    E = np.outer(act_hist, pred_hist)
    
    E = E / E.sum()
    O = O / O.sum()
    
    
    top = np.multiply(W,O).sum()
    bottom = np.multiply(W,E).sum()
    
    kappa = 1 - (top/bottom)

    kappas[i] = kappa
    
plt.hist(kappas)


# train['R1'] = train['Response'] == 1
# train['R2'] = train['Response'] == 2
# train['R3'] = train['Response'] == 3
# train['R4'] = train['Response'] == 4
# train['R5'] = train['Response'] == 5
# train['R6'] = train['Response'] == 6
# train['R7'] = train['Response'] == 7
# train['R8'] = train['Response'] == 8

# test = pd.read_csv('test.csv')
